### ISSUE TITLE
Needs to catch another "connection reset by peer" error

### ISSUE THREAD

**Issue by kcmannem** [concourse/retryhttp#6]
We need to have the retryer work for the lower case version "connection reset by peer". We only catch the one provided by the syscall package which is actually a string with capitcal "Connection"

```
func main() {
	fmt.Println(syscall.ECONNRESET) // Connection reset by peer
        fmt.Println(strings.HasSuffix(syscall.ECONNRESET.Error(), "connection reset by peer")) // false
}
```

We failed to retry in strabo and errored with the lowercase version
```
Put /volumes/8194d746-5f35-4b41-7f51-eaba30eb2a84/stream-in?path=.: read tcp 10.11.7.28:41336->10.11.7.27:46617: read: connection reset by peer
```

**Comment by vito** [comment]
fixed by #7
